apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  serviceAccountName: default
  chart:
    spec:
      chart: ingress-nginx      
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 5m
  install:
    remediation:
      retries: 3
